### ISSUE TITLE
Adding a Package or Modpack errors trying to get ID of non-object

### ISSUE THREAD

**Issue by Lord-Ptolemy** [SolderIO/solder#120] opened 2018-04-08 20:12 UTC
Tried adding my first package which was Forge and I get this on submission:

Form Data:
```
_token:<redacted>
name:Minecraft Forge
slug:minecraft-forge
author:Forge Development LLC
website_url:https://minecraftforge.net/
donation_url:
description:
```

Error:
```
ErrorException thrown with message "Trying to get property 'id' of non-object"

Stacktrace:
#68 ErrorException in /var/www/solder.uskarian.net/app/CanJoinTeams.php:65
#67 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /var/www/solder.uskarian.net/app/CanJoinTeams.php:65
#66 App\User:switchToTeam in /var/www/solder.uskarian.net/app/CanJoinTeams.php:50
#65 App\User:currentTeam in /var/www/solder.uskarian.net/app/CanJoinTeams.php:39
#64 App\User:getCurrentTeamAttribute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:444
#63 Illuminate\Database\Eloquent\Model:mutateAttribute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:344
#62 Illuminate\Database\Eloquent\Model:getAttributeValue in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:317
#61 Illuminate\Database\Eloquent\Model:getAttribute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1416
#60 Illuminate\Database\Eloquent\Model:__get in /var/www/solder.uskarian.net/app/Http/Controllers/PackagesController.php:75
#59 App\Http\Controllers\PackagesController:store in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#58 call_user_func_array in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#57 Illuminate\Routing\Controller:callAction in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#56 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
#55 Illuminate\Routing\Route:runController in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
#54 Illuminate\Routing\Route:run in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:659
#53 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php:50
#51 Laravel\Passport\Http\Middleware\CreateFreshApiToken:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#48 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#45 Illuminate\Auth\Middleware\Authenticate:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
#42 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#39 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#36 Illuminate\Session\Middleware\StartSession:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#33 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
#30 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#27 Illuminate\Pipeline\Pipeline:then in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:661
#26 Illuminate\Routing\Router:runRouteWithinStack in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636
#25 Illuminate\Routing\Router:runRoute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:602
#24 Illuminate\Routing\Router:dispatchToRoute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:591
#23 Illuminate\Routing\Router:dispatch in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#22 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#21 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:65
#20 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/fideloper/proxy/src/TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/solder.uskarian.net/public/index.php:55
```

Seems to be an issue with it not getting a team?

**Comment by Lord-Ptolemy** [comment] 2018-04-08 20:18
This is also an issue when trying to create a modpack.

Form Data:
```
_token:<redacted>
name:agrimaxima
slug:agrimaxima
status:draft
```

Error:
```
ErrorException thrown with message "Trying to get property 'id' of non-object"

Stacktrace:
#68 ErrorException in /var/www/solder.uskarian.net/app/CanJoinTeams.php:65
#67 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /var/www/solder.uskarian.net/app/CanJoinTeams.php:65
#66 App\User:switchToTeam in /var/www/solder.uskarian.net/app/CanJoinTeams.php:50
#65 App\User:currentTeam in /var/www/solder.uskarian.net/app/CanJoinTeams.php:39
#64 App\User:getCurrentTeamAttribute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:444
#63 Illuminate\Database\Eloquent\Model:mutateAttribute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:344
#62 Illuminate\Database\Eloquent\Model:getAttributeValue in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:317
#61 Illuminate\Database\Eloquent\Model:getAttribute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1416
#60 Illuminate\Database\Eloquent\Model:__get in /var/www/solder.uskarian.net/app/Http/Controllers/ModpacksController.php:63
#59 App\Http\Controllers\ModpacksController:store in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#58 call_user_func_array in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#57 Illuminate\Routing\Controller:callAction in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#56 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
#55 Illuminate\Routing\Route:runController in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
#54 Illuminate\Routing\Route:run in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:659
#53 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php:50
#51 Laravel\Passport\Http\Middleware\CreateFreshApiToken:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#48 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#45 Illuminate\Auth\Middleware\Authenticate:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
#42 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#39 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#36 Illuminate\Session\Middleware\StartSession:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#33 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
#30 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#27 Illuminate\Pipeline\Pipeline:then in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:661
#26 Illuminate\Routing\Router:runRouteWithinStack in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636
#25 Illuminate\Routing\Router:runRoute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:602
#24 Illuminate\Routing\Router:dispatchToRoute in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php:591
#23 Illuminate\Routing\Router:dispatch in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#22 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#21 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:65
#20 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/fideloper/proxy/src/TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/solder.uskarian.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/solder.uskarian.net/public/index.php:55
```

**Comment by Indemnity83** [comment] 2018-04-08 21:18
Thanks. Looks like I forgot to add the team stuff on create. I thought I had test coverage of this. 

I actually have a whole new api and front end to drop in here so I may skip fixing this bug for the larger fix.

Keeping it open either way though until one happens.

**Comment by Lord-Ptolemy** [comment] 2018-04-08 23:43
If the new api and frontend are coming soon then I would just skip fixing this bug.

**Comment by Indemnity83** [comment] 2018-04-13 20:20
Looking through this stack trace again I'm actually not certain that your error is caused by a bug in the code. 

There were changes made to the database level in some previous commits that if you didn't do manually might have caused this error to occur. So did you get this error after doing an update on your installation without wiping out the database?

**Comment by Pyker** [comment] 2023-06-28 18:57
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.

**Closed as not planned by Pyker** 2023-06-28 18:57 UTC
